apiVersion: v1
kind: Service
metadata:
  name: flaskkubernetesworkflow
  namespace: namespace-workflow-1687927487856
spec:
  type: LoadBalancer
  selector:
    app: flaskkubernetesworkflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000